print("benvenuto nell creatore degli account")
print("ora creiamo il tuo account per riuscire ad accedere alla saga di 'PenRide'")
print("Il tuo account e password li imposterai tu")
print("inserisci nome utente")
nom = input()
print("ora inserisci password")
passw = input()
print("ok ora che hai creato il tuo account puoi uscire e usralo in tutte le app")
print("digita 'esci' per uscire")
esci = input()